version: '3.0' # Note that the verison is NOT for this document, but for the version of docker-compose itself. Keep.
services:
  elasticsearch:
    image: elasticsearch:6.4.0
    container_name: harv_search
    restart: always
    environment:
      - RAILS_ENV
      - bootstrap.memory_lock=true
      - cluster.name=eol-search-${RAILS_ENV}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./templates/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${EOL_ROOT_DIR}/elasticsearch/data:/var/data/elasticsearch
      - ${EOL_ROOT_DIR}/elasticsearch/log:/var/log/elasticsearch
    networks:
      - docker_eolnet
    ports:
      - 9200:9200
      - 9300:9300
  elasticsearch2:
    image: elasticsearch:6.4.0
    container_name: harv_search2
    environment:
      - RAILS_ENV
      - cluster.name=eol-search-${RAILS_ENV}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=[eol-backend-elasticsearch,eol-backend-elasticsearch3]"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./templates/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${EOL_ROOT_DIR}/elasticsearch2/data:/var/data/elasticsearch
      - ${EOL_ROOT_DIR}/elasticsearch2/log:/var/log/elasticsearch
    networks:
      - docker_eolnet
  elasticsearch3:
    image: elasticsearch:6.4.0
    container_name: harv_search3
    environment:
      - cluster.name=eol-search-${RAILS_ENV}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=[eol-backend-elasticsearch,eol-backend-elasticsearch2]"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./templates/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${EOL_ROOT_DIR}/elasticsearch3/data:/var/data/elasticsearch
      - ${EOL_ROOT_DIR}/elasticsearch3/log:/var/log/elasticsearch
    networks:
      - docker_eolnet
  memcached:
    image: memcached
    container_name: harv_cache
    restart: always
    environment:
      - TZ=America/New_York
    command: memcached -m 4096m
    networks:
      - docker_eolnet
  mysql:
    image: mysql:5.7.12
    container_name: harv_db
    restart: always
    env_file:
      - resources/staging.env
    volumes:
      - ${EOL_ROOT_DIR}/mysql:/var/lib/mysql
    networks:
      - docker_eolnet
  web:
    build: ..
    image: harvester_v3
    container_name: web
    restart: always
    volumes:
      - ./resources/secrets.yml:/app/config/secrets.yml
      - ${EOL_ROOT_DIR}/web/app/public/data
      - ${EOL_ROOT_DIR}/web/tmp:/tmp
    depends_on:
      - elasticsearch
      - mysql
      - memcached
    links:
      - elasticsearch
      - memcached
      - mysql
    env_file:
      - resources/staging.env
    ports:
      - 3001:3000
    networks:
      - docker_eolnet
networks:
  docker_eolnet:
    external: true
