staging:
  db:
    host: localhost
    port: 3306
    username: test
    password: not2_secüre
    name: eol_web_development
  web_db:
    username: test
    password: not2_secure_eithe®
    database: eol_web_development
    host: localhost
    port: 3306
  secret_key_base: abcdef123456789
  google_maps_key: 12345678910987654321
  discourse_url: "http://discuss.eol.org"
  discourse_user: jrice
  discourse_key: 8888777766664444
  new_relic_key: 1234abcde5e5e5e5
  host:
    name: localhost
    url: 'https://development.eol.org'
  smtp:
    address: stmp_host
    domain: 'eol.org'
  repository:
    url: 'https://development_content.eol.org'
  image_path:
    original: '' # Yes, nothing.
    ext: '.jpg'
    join: '.'
    by: 'x'
  traitbank_url: 'http://neo4j_username:password_here@neo4j:7474'
  cache_url: 'memcached:11211'
